#pragma once

#define INSTR_OPCODE_OFFSET 0
#define INSTR_RS1_OFFSET (INSTR_OPCODE_OFFSET+8)
#define INSTR_RS2_OFFSET (INSTR_RS1_OFFSET+5)
#define INSTR_RD_OFFSET (INSTR_RS2_OFFSET+5)
#define INSTR_IMM_OFFSET (INSTR_RD_OFFSET+6)

#define INSTR_OPCODE_MASK  (0xFF << INSTR_OPCODE_OFFSET)
#define INSTR_RS1_MASK     (0x1F << INSTR_RS1_OFFSET)
#define INSTR_RS2_MASK     (0x1F << INSTR_RS2_OFFSET)
#define INSTR_RD_MASK      (0x1F << INSTR_RD_OFFSET)
#define INSTR_IMM_MASK     (0xFF << INSTR_IMM_OFFSET)

#define GET_OPCODE(val) ((val & INSTR_OPCODE_MASK) >> INSTR_OPCODE_OFFSET)
#define GET_RS1(val) ((val & INSTR_RS1_MASK) >> INSTR_RS1_OFFSET)
#define GET_RS2(val) ((val & INSTR_RS2_MASK) >> INSTR_RS2_OFFSET)
#define GET_RD(val) ((val & INSTR_RD_MASK) >> INSTR_RD_OFFSET)
#define GET_IMM(val) ((int32_t)(((val & INSTR_IMM_MASK) >> INSTR_IMM_OFFSET) - 0x80))

#define INSTR_LD        0b00000010
#define INSTR_SD        0b00000011
#define INSTR_ADD       0b00001000
#define INSTR_HLT       0b00000000
